use_frameworks!

target 'ZXMarsKit_Example' do
  pod 'ZXMarsKit', :path => '../'

  target 'ZXMarsKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
